
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel1_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                Date = @"2022-02-25",
                Day = 2F,
                Personnel = 2800F,
                Personnel_ = @"about",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual POW with predicted POW from sample data...\n\n");


            Console.WriteLine($"Date: {@"2022-02-25"}");
            Console.WriteLine($"Day: {2F}");
            Console.WriteLine($"Personnel: {2800F}");
            Console.WriteLine($"Personnel_: {@"about"}");
            Console.WriteLine($"POW: {0F}");


            Console.WriteLine($"\n\nPredicted POW: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
